# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake/bin/cmake

# The command to remove a file.
RM = /opt/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /src/logic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /src/CMakeFiles /src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named logic

# Build rule for target.
logic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logic
.PHONY : logic

# fast build rule for target.
logic/fast:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/build
.PHONY : logic/fast

#=============================================================================
# Target rules for targets named logic-test

# Build rule for target.
logic-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logic-test
.PHONY : logic-test

# fast build rule for target.
logic-test/fast:
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/build
.PHONY : logic-test/fast

LogicGate.o: LogicGate.cpp.o

.PHONY : LogicGate.o

# target to build an object file
LogicGate.cpp.o:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/LogicGate.cpp.o
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/LogicGate.cpp.o
.PHONY : LogicGate.cpp.o

LogicGate.i: LogicGate.cpp.i

.PHONY : LogicGate.i

# target to preprocess a source file
LogicGate.cpp.i:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/LogicGate.cpp.i
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/LogicGate.cpp.i
.PHONY : LogicGate.cpp.i

LogicGate.s: LogicGate.cpp.s

.PHONY : LogicGate.s

# target to generate assembly for a file
LogicGate.cpp.s:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/LogicGate.cpp.s
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/LogicGate.cpp.s
.PHONY : LogicGate.cpp.s

LogicTest.o: LogicTest.cpp.o

.PHONY : LogicTest.o

# target to build an object file
LogicTest.cpp.o:
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/LogicTest.cpp.o
.PHONY : LogicTest.cpp.o

LogicTest.i: LogicTest.cpp.i

.PHONY : LogicTest.i

# target to preprocess a source file
LogicTest.cpp.i:
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/LogicTest.cpp.i
.PHONY : LogicTest.cpp.i

LogicTest.s: LogicTest.cpp.s

.PHONY : LogicTest.s

# target to generate assembly for a file
LogicTest.cpp.s:
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/LogicTest.cpp.s
.PHONY : LogicTest.cpp.s

Tree.o: Tree.cpp.o

.PHONY : Tree.o

# target to build an object file
Tree.cpp.o:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/Tree.cpp.o
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/Tree.cpp.o
.PHONY : Tree.cpp.o

Tree.i: Tree.cpp.i

.PHONY : Tree.i

# target to preprocess a source file
Tree.cpp.i:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/Tree.cpp.i
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/Tree.cpp.i
.PHONY : Tree.cpp.i

Tree.s: Tree.cpp.s

.PHONY : Tree.s

# target to generate assembly for a file
Tree.cpp.s:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/Tree.cpp.s
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/Tree.cpp.s
.PHONY : Tree.cpp.s

expressionparser.o: expressionparser.cpp.o

.PHONY : expressionparser.o

# target to build an object file
expressionparser.cpp.o:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/expressionparser.cpp.o
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/expressionparser.cpp.o
.PHONY : expressionparser.cpp.o

expressionparser.i: expressionparser.cpp.i

.PHONY : expressionparser.i

# target to preprocess a source file
expressionparser.cpp.i:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/expressionparser.cpp.i
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/expressionparser.cpp.i
.PHONY : expressionparser.cpp.i

expressionparser.s: expressionparser.cpp.s

.PHONY : expressionparser.s

# target to generate assembly for a file
expressionparser.cpp.s:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/expressionparser.cpp.s
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/expressionparser.cpp.s
.PHONY : expressionparser.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/main.cpp.s
.PHONY : main.cpp.s

statement.o: statement.cpp.o

.PHONY : statement.o

# target to build an object file
statement.cpp.o:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/statement.cpp.o
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/statement.cpp.o
.PHONY : statement.cpp.o

statement.i: statement.cpp.i

.PHONY : statement.i

# target to preprocess a source file
statement.cpp.i:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/statement.cpp.i
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/statement.cpp.i
.PHONY : statement.cpp.i

statement.s: statement.cpp.s

.PHONY : statement.s

# target to generate assembly for a file
statement.cpp.s:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/statement.cpp.s
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/statement.cpp.s
.PHONY : statement.cpp.s

statementevaluator.o: statementevaluator.cpp.o

.PHONY : statementevaluator.o

# target to build an object file
statementevaluator.cpp.o:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/statementevaluator.cpp.o
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/statementevaluator.cpp.o
.PHONY : statementevaluator.cpp.o

statementevaluator.i: statementevaluator.cpp.i

.PHONY : statementevaluator.i

# target to preprocess a source file
statementevaluator.cpp.i:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/statementevaluator.cpp.i
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/statementevaluator.cpp.i
.PHONY : statementevaluator.cpp.i

statementevaluator.s: statementevaluator.cpp.s

.PHONY : statementevaluator.s

# target to generate assembly for a file
statementevaluator.cpp.s:
	$(MAKE) -f CMakeFiles/logic.dir/build.make CMakeFiles/logic.dir/statementevaluator.cpp.s
	$(MAKE) -f CMakeFiles/logic-test.dir/build.make CMakeFiles/logic-test.dir/statementevaluator.cpp.s
.PHONY : statementevaluator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... logic"
	@echo "... logic-test"
	@echo "... LogicGate.o"
	@echo "... LogicGate.i"
	@echo "... LogicGate.s"
	@echo "... LogicTest.o"
	@echo "... LogicTest.i"
	@echo "... LogicTest.s"
	@echo "... Tree.o"
	@echo "... Tree.i"
	@echo "... Tree.s"
	@echo "... expressionparser.o"
	@echo "... expressionparser.i"
	@echo "... expressionparser.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... statement.o"
	@echo "... statement.i"
	@echo "... statement.s"
	@echo "... statementevaluator.o"
	@echo "... statementevaluator.i"
	@echo "... statementevaluator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

